cache:
  directories:
  - $HOME/.m2
language: java
jdk: oraclejdk8
install:
  - mvn -B -Pdeploy --settings .travis-settings.xml -V dependency:go-offline
script:
  - mvn -B -Pdeploy --settings .travis-settings.xml -Dgpg.skip=true verify
notifications:
  email:
    - ben.alex@acegi.com.au
